# -*- coding: utf-8 -*-
import scrapy,json
from scrapy.http import Request

from tutorial.items import *
class ChepaiSpider(scrapy.Spider):
    name = 'chepai'
    # 设置headers伪装成浏览器
    headers = {
        'User-Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/536.5 (KHTML, like Gecko) Chrome/19.0.1084.54 Safari/536.5'
    }

    # 指定url的情况下我们重写start_requests方法
    def start_requests(self):
        li =[]
        li.append(u"皖A")
        li.append(u"皖B")
        li.append(u"皖C")
        li.append(u"皖D")
        li.append(u"皖E")
        li.append(u"皖F")
        li.append(u"皖G")
        li.append(u"皖H")
        li.append(u"皖J")
        li.append(u"皖K")
        li.append(u"皖L")
        li.append(u"皖M")
        li.append(u"皖N")
        li.append(u"皖P")
        li.append(u"皖Q")
        li.append(u"皖R")
        li.append(u"皖S")
        li.append(u"京A")
        li.append(u"京B")
        li.append(u"京C")
        li.append(u"京D")
        li.append(u"京E")
        li.append(u"京F")
        li.append(u"京G")
        li.append(u"京H")
        li.append(u"京J")
        li.append(u"京K")
        li.append(u"京L")
        li.append(u"京M")
        li.append(u"京Y")
        li.append(u"渝A")
        li.append(u"渝B")
        li.append(u"渝C")
        li.append(u"渝D")
        li.append(u"渝F")
        li.append(u"渝G")
        li.append(u"渝H")
        li.append(u"闽A")
        li.append(u"闽B")
        li.append(u"闽C")
        li.append(u"闽D")
        li.append(u"闽E")
        li.append(u"闽F")
        li.append(u"闽G")
        li.append(u"闽H")
        li.append(u"闽J")
        li.append(u"闽K")
        li.append(u"甘A")
        li.append(u"甘B")
        li.append(u"甘C")
        li.append(u"甘D")
        li.append(u"甘E")
        li.append(u"甘F")
        li.append(u"甘G")
        li.append(u"甘H")
        li.append(u"甘J")
        li.append(u"甘K")
        li.append(u"甘L")
        li.append(u"甘M")
        li.append(u"甘N")
        li.append(u"甘P")
        li.append(u"粤A")
        li.append(u"粤B")
        li.append(u"粤C")
        li.append(u"粤D")
        li.append(u"粤E")
        li.append(u"粤F")
        li.append(u"粤G")
        li.append(u"粤H")
        li.append(u"粤J")
        li.append(u"粤K")
        li.append(u"粤L")
        li.append(u"粤M")
        li.append(u"粤N")
        li.append(u"粤P")
        li.append(u"粤Q")
        li.append(u"粤R")
        li.append(u"粤S")
        li.append(u"粤T")
        li.append(u"粤U")
        li.append(u"粤V")
        li.append(u"粤W")
        li.append(u"粤X")
        li.append(u"粤Y")
        li.append(u"粤Z")
        li.append(u"桂A")
        li.append(u"桂B")
        li.append(u"桂C")
        li.append(u"桂D")
        li.append(u"桂E")
        li.append(u"桂F")
        li.append(u"桂G")
        li.append(u"桂H")
        li.append(u"桂J")
        li.append(u"桂K")
        li.append(u"桂L")
        li.append(u"桂M")
        li.append(u"桂N")
        li.append(u"桂P")
        li.append(u"桂R")
        li.append(u"贵A")
        li.append(u"贵B")
        li.append(u"贵C")
        li.append(u"贵D")
        li.append(u"贵E")
        li.append(u"贵F")
        li.append(u"贵G")
        li.append(u"贵H")
        li.append(u"贵J")
        li.append(u"琼A")
        li.append(u"琼B")
        li.append(u"琼C")
        li.append(u"琼D")
        li.append(u"琼E")
        li.append(u"冀A")
        li.append(u"冀B")
        li.append(u"冀C")
        li.append(u"冀D")
        li.append(u"冀E")
        li.append(u"冀F")
        li.append(u"冀G")
        li.append(u"冀H")
        li.append(u"冀J")
        li.append(u"冀R")
        li.append(u"冀S")
        li.append(u"冀T")
        li.append(u"豫A")
        li.append(u"豫B")
        li.append(u"豫C")
        li.append(u"豫D")
        li.append(u"豫E")
        li.append(u"豫F")
        li.append(u"豫G")
        li.append(u"豫H")
        li.append(u"豫J")
        li.append(u"豫K")
        li.append(u"豫L")
        li.append(u"豫M")
        li.append(u"豫N")
        li.append(u"豫P")
        li.append(u"豫Q")
        li.append(u"豫R")
        li.append(u"豫S")
        li.append(u"豫U")
        li.append(u"黑A")
        li.append(u"黑B")
        li.append(u"黑C")
        li.append(u"黑D")
        li.append(u"黑E")
        li.append(u"黑F")
        li.append(u"黑G")
        li.append(u"黑H")
        li.append(u"黑J")
        li.append(u"黑K")
        li.append(u"黑L")
        li.append(u"黑M")
        li.append(u"黑N")
        li.append(u"黑P")
        li.append(u"黑R")
        li.append(u"鄂A")
        li.append(u"鄂B")
        li.append(u"鄂C")
        li.append(u"鄂D")
        li.append(u"鄂E")
        li.append(u"鄂F")
        li.append(u"鄂G")
        li.append(u"鄂H")
        li.append(u"鄂J")
        li.append(u"鄂K")
        li.append(u"鄂L")
        li.append(u"鄂M")
        li.append(u"鄂N")
        li.append(u"鄂P")
        li.append(u"鄂Q")
        li.append(u"鄂R")
        li.append(u"鄂S")
        li.append(u"湘A")
        li.append(u"湘B")
        li.append(u"湘C")
        li.append(u"湘D")
        li.append(u"湘E")
        li.append(u"湘F")
        li.append(u"湘G")
        li.append(u"湘H")
        li.append(u"湘J")
        li.append(u"湘K")
        li.append(u"湘L")
        li.append(u"湘M")
        li.append(u"湘N")
        li.append(u"湘U")
        li.append(u"吉A")
        li.append(u"吉B")
        li.append(u"吉C")
        li.append(u"吉D")
        li.append(u"吉E")
        li.append(u"吉F")
        li.append(u"吉G")
        li.append(u"吉H")
        li.append(u"吉J")
        li.append(u"吉K")
        li.append(u"苏A")
        li.append(u"苏B")
        li.append(u"苏C")
        li.append(u"苏D")
        li.append(u"苏E")
        li.append(u"苏F")
        li.append(u"苏G")
        li.append(u"苏H")
        li.append(u"苏J")
        li.append(u"苏K")
        li.append(u"苏L")
        li.append(u"苏M")
        li.append(u"苏N")
        li.append(u"赣A")
        li.append(u"赣B")
        li.append(u"赣C")
        li.append(u"赣D")
        li.append(u"赣E")
        li.append(u"赣F")
        li.append(u"赣G")
        li.append(u"赣H")
        li.append(u"赣J")
        li.append(u"赣K")
        li.append(u"赣L")
        li.append(u"赣M")
        li.append(u"辽A")
        li.append(u"辽B")
        li.append(u"辽C")
        li.append(u"辽D")
        li.append(u"辽E")
        li.append(u"辽F")
        li.append(u"辽G")
        li.append(u"辽H")
        li.append(u"辽J")
        li.append(u"辽K")
        li.append(u"辽L")
        li.append(u"辽M")
        li.append(u"辽N")
        li.append(u"辽P")
        li.append(u"宁A")
        li.append(u"宁B")
        li.append(u"宁C")
        li.append(u"宁D")
        li.append(u"宁E")
        li.append(u"蒙A")
        li.append(u"蒙B")
        li.append(u"蒙C")
        li.append(u"蒙D")
        li.append(u"蒙E")
        li.append(u"蒙F")
        li.append(u"蒙G")
        li.append(u"蒙H")
        li.append(u"蒙J")
        li.append(u"蒙K")
        li.append(u"蒙L")
        li.append(u"蒙M")
        li.append(u"青A")
        li.append(u"青B")
        li.append(u"青C")
        li.append(u"青D")
        li.append(u"青E")
        li.append(u"青F")
        li.append(u"青G")
        li.append(u"青H")
        li.append(u"鲁A")
        li.append(u"鲁B")
        li.append(u"鲁C")
        li.append(u"鲁D")
        li.append(u"鲁E")
        li.append(u"鲁F")
        li.append(u"鲁G")
        li.append(u"鲁H")
        li.append(u"鲁J")
        li.append(u"鲁K")
        li.append(u"鲁L")
        li.append(u"鲁M")
        li.append(u"鲁N")
        li.append(u"鲁P")
        li.append(u"鲁Q")
        li.append(u"鲁R")
        li.append(u"鲁S")
        li.append(u"鲁U")
        li.append(u"鲁V")
        li.append(u"鲁Y")
        li.append(u"晋A")
        li.append(u"晋B")
        li.append(u"晋C")
        li.append(u"晋D")
        li.append(u"晋E")
        li.append(u"晋F")
        li.append(u"晋G")
        li.append(u"晋H")
        li.append(u"晋J")
        li.append(u"晋K")
        li.append(u"晋L")
        li.append(u"晋M")
        li.append(u"陕A")
        li.append(u"陕B")
        li.append(u"陕C")
        li.append(u"陕D")
        li.append(u"陕E")
        li.append(u"陕F")
        li.append(u"陕G")
        li.append(u"陕H")
        li.append(u"陕J")
        li.append(u"陕K")
        li.append(u"陕V")
        li.append(u"沪A")
        li.append(u"沪B")
        li.append(u"沪C")
        li.append(u"沪D")
        li.append(u"沪R")
        li.append(u"川A")
        li.append(u"沪B")
        li.append(u"沪C")
        li.append(u"沪D")
        li.append(u"沪E")
        li.append(u"沪F")
        li.append(u"沪G")
        li.append(u"沪H")
        li.append(u"沪J")
        li.append(u"沪K")
        li.append(u"沪L")
        li.append(u"沪M")
        li.append(u"沪N")
        li.append(u"沪R")
        li.append(u"沪S")
        li.append(u"沪T")
        li.append(u"沪U")
        li.append(u"沪V")
        li.append(u"沪W")
        li.append(u"沪X")
        li.append(u"沪Y")
        li.append(u"沪Z")
        li.append(u"津A")
        li.append(u"津B")
        li.append(u"津C")
        li.append(u"津D")
        li.append(u"津E")
        li.append(u"津F")
        li.append(u"津G")
        li.append(u"津H")
        li.append(u"藏A")
        li.append(u"藏B")
        li.append(u"藏C")
        li.append(u"藏D")
        li.append(u"藏E")
        li.append(u"藏F")
        li.append(u"藏G")
        li.append(u"藏H")
        li.append(u"藏J")
        li.append(u"新A")
        li.append(u"新B")
        li.append(u"新C")
        li.append(u"新D")
        li.append(u"新E")
        li.append(u"新F")
        li.append(u"新G")
        li.append(u"新H")
        li.append(u"新J")
        li.append(u"新K")
        li.append(u"新L")
        li.append(u"新M")
        li.append(u"新N")
        li.append(u"新R")
        li.append(u"云A")
        li.append(u"云B")
        li.append(u"云C")
        li.append(u"云D")
        li.append(u"云E")
        li.append(u"云F")
        li.append(u"云G")
        li.append(u"云H")
        li.append(u"云J")
        li.append(u"云K")
        li.append(u"云L")
        li.append(u"云M")
        li.append(u"云N")
        li.append(u"云R")
        li.append(u"云S")
        li.append(u"云V")
        li.append(u"浙A")
        li.append(u"浙B")
        li.append(u"浙C")
        li.append(u"浙D")
        li.append(u"浙E")
        li.append(u"浙F")
        li.append(u"浙G")
        li.append(u"浙H")
        li.append(u"浙J")
        li.append(u"浙K")
        li.append(u"浙L")
        # 港澳 大使馆


        # 车牌颜色
        li_color=[]
        li_color.append("黄色车牌")
        li_color.append("黑色车牌")
        li_color.append("白色车牌")
        li_color.append("绿色车牌")


        for it in li_color:
            self.key= it
            self.number=300;

            # self.path =u"/pic/" + self.key


            # start_urls = 'https://image.baidu.com/search/acjson?tn=resultjson_com&ipn=rj&ct=201326592&is=&fp=result&queryWord='+key+'&cl=2&lm=-1&ie=utf-8&oe=utf-8&adpicid=&st=-1&z=&ic=0&word='+key+'&s=&se=&tab=&width=&height=&face=0&istype=2&qc=&nc=1&fr=&pn=900&rn=30'
            start_urls =[
                 'https://image.baidu.com/search/acjson?tn=resultjson_com&ipn=rj&ct=201326592&is=&fp=result&queryWord='+self.key+'&cl=2&lm=-1&ie=utf-8&oe=utf-8&adpicid=&st=-1&z=&ic=0&word='+self.key+'&s=&se=&tab=&width=&height=&face=0&istype=2&qc=&nc=1&fr=&pn=%d&rn=30' %i for i in range(0,self.number,30)
            ]
            # yield Request(start_urls,headers=self.headers)
            for url in start_urls:
                yield Request(url,headers=self.headers)

    def parse(self, response):
        #从Json文件内容中提取所有img的内容
        imgs = json.loads(response.body)['data']
        _KEY_ = json.loads(response.body)['queryExt']
        for eachImage in imgs:
            item = TutorialItem()  #items中的类
            try:
                item['image_url'] = [eachImage['middleURL']]
                item['image_path']= u"/pic/" + _KEY_
                yield item
            except Exception as e:
                print(e)



